site_name: Terra Docs
pages:
  - [index.md, 'Home']
  - [install.md, 'General', 'Install']
  - [example-setup.md, 'openFDA', 'Setup Example: openFDA']
  - [drupal.md, 'General', 'Setting up a Drupal Site']
  - [containers.md, 'General', 'Docker Container Strategy']
  - [development.md, 'General', 'Developing Terra']
  - [workflow.md, 'General', 'Terra App Workflow']
theme: readthedocs
site_author: ""
repo_url: https://github.com/terra-ops/terra-app
